const ORDER_STATUSES = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED'
};

const ALLOWED_TRANSITIONS = {
  [ORDER_STATUSES.CREATED]: [ORDER_STATUSES.ASSIGNED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.ASSIGNED]: [ORDER_STATUSES.PICKED_UP, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.PICKED_UP]: [ORDER_STATUSES.IN_TRANSIT, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.IN_TRANSIT]: [ORDER_STATUSES.OUT_FOR_DELIVERY, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.DELIVERED, ORDER_STATUSES.FAILED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.FAILED]: [ORDER_STATUSES.RESCHEDULED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.RESCHEDULED]: [ORDER_STATUSES.ASSIGNED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.DELIVERED]: [],
  [ORDER_STATUSES.CANCELLED]: []
};

const ROLE_TRANSITION_PERMISSIONS = {
  AGENT: {
    [ORDER_STATUSES.ASSIGNED]: [ORDER_STATUSES.PICKED_UP],
    [ORDER_STATUSES.PICKED_UP]: [ORDER_STATUSES.IN_TRANSIT],
    [ORDER_STATUSES.IN_TRANSIT]: [ORDER_STATUSES.OUT_FOR_DELIVERY],
    [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.DELIVERED, ORDER_STATUSES.FAILED]
  },
  CUSTOMER: {
    [ORDER_STATUSES.FAILED]: [ORDER_STATUSES.RESCHEDULED]
  }
};

function isValidTransition(currentStatus, targetStatus) {
  const allowed = ALLOWED_TRANSITIONS[currentStatus] || [];
  return allowed.includes(targetStatus);
}

function isRoleAllowedTransition(role, currentStatus, targetStatus) {
  if (role === 'ADMIN' || role === 'SYSTEM') {
    return isValidTransition(currentStatus, targetStatus);
  }

  const roleRules = ROLE_TRANSITION_PERMISSIONS[role];
  if (!roleRules) return false;

  const allowedForStatus = roleRules[currentStatus] || [];
  return allowedForStatus.includes(targetStatus);
}

module.exports = {
  ORDER_STATUSES,
  ALLOWED_TRANSITIONS,
  ROLE_TRANSITION_PERMISSIONS,
  isValidTransition,
  isRoleAllowedTransition
};
